In [1]:
#@author- Tejasvi Sharma
'''The main purpose of this file is to load data from three different sheets from an excel file and combine them. 
   After this we filter out the data only for last ten years and only for G20 Countries'''
#Importing librarias required for project
import pandas as pd#for dataframes
import matplotlib.pyplot as plt # for plots
from IPython.display import display

In [2]:
try:
    #Loading data for military spending per capita
    df_cap=pd.read_excel("sipri.xlsx",sheetname="Per capita") # values is in US dollars
    del df_cap["Notes"] #removing Notes Column from dataframe

    #Loading data for military Spending
    df=pd.read_excel("sipri.xlsx",sheetname="Current USD") # values is in millions US dollars
    del df["Notes"] #removing Notes Column from dataframe

    #Loading data for military Spending as share of GDP
    df_gdp=pd.read_excel("sipri.xlsx",sheetname="Share of GDP")
    del df_gdp["Notes"] # removing Notes Column from dataframe
except Exception as e:
    print(e)

In [3]:
#the aim of this function to select data from only last ten years and then filter out that data for only G20 countries
#@param - df: Dataframe from which data for G20 countries and data only for last years is extracted
#@param - newColName: Column name of new column after stack
def func_select(df,newColName):
    #This DataFrame has data from 1949 to 2016 and we are interested in Only data from last ten years, so we will filter those
    #columns
    df=df.set_index('Country')
    Years=[i for i in range(2016-10+1,2016+1)] #2016 is the last year, we want last ten years
    df=df[Years] # So now we have data for all countries in our file but for only 10 years,but we are Interested in only G20
    #Countries,So we will filter out g20 countries
    g20=["Argentina","Australia","Brazil","Canada","China, P.R.","France","Germany","India","Indonesia","Italy","Japan","Mexico","Russian Federation","Saudi Arabia","South Africa","Korea, South","Turkey","UK","USA"]
    df=df.loc[g20]
    data=pd.DataFrame(df.stack(),columns=[newColName])
    data1=data.reset_index().rename(columns={'level_1': 'Year'}).set_index(['Year','Country']).sort_index()
    return data1

In [4]:
#applying function func_select on the three data frames dataframes
df_cap1=func_select(df_cap,"Military_spending_per_capita")
df_gdp1=func_select(df_gdp,"Military_spending_gdp")
df1=func_select(df,"Military_spending")

In [5]:
# joining all the three data frames to one named dataframe
dataframe=df_cap1.join(df_gdp1).join(df1)
#dataframe["Gdp"]=dataframe["Military_spending"]/dataframe["Military_spending_gdp"]/1000 #GDP in billions
#Calculating GDP
dataframe["Gdp"]=dataframe["Military_spending"]/dataframe["Military_spending_gdp"] #GDP in millions
#Calculating Population 
dataframe["Pop"]=dataframe["Military_spending"]/(dataframe["Military_spending_per_capita"]/1000000) #population 
#convert population to millions
dataframe["Pop"]=dataframe["Pop"]/1000000
#saving dataframe to a csv file in Documents folder with mode as write, so if an older file exists it will be overwritten
dataframe=dataframe.dropna() # to drop rows with null values
try:
    dataframe.to_csv("DataMiningProjectData.csv",mode = 'w',sep='\t')
except Exception as e:
    print(e)
dataframe

                        Military_spending_per_capita Military_spending_gdp  \
Year Country
2007 Argentina                               57.4544            0.00875001
     Australia                                819.34             0.0181602
     Brazil                                  106.262             0.0149876
     Canada                                  528.076             0.0122159
     China, P.R.                             51.5385             0.0191995
     France                                  977.872             0.0227448
     Germany                                 526.277             0.0123859
     India                                   23.9511             0.0234263
     Indonesia                               14.4159            0.00774787
     Italy                                   608.092             0.0163168
     Japan                                   318.507            0.00930372
     Korea, South                             575.17             0.0247738
     Mexico                                  42.2473            0.00458222
     Russian Federation                      304.057             0.0338816
     Saudi Arabia                            1359.84             0.0852704
     South Africa                            70.9485             0.0123203
     Turkey                                   220.37             0.0236721
     UK                                      1079.05              0.022268
     USA                                     1846.35             0.0384705
2008 Argentina                               69.0652            0.00844643
     Australia                               871.913             0.0179848
     Brazil                                  125.548             0.0147883
     Canada                                  579.741             0.0128793
     China, P.R.                             65.0959             0.0189203
     France                                  1059.38             0.0225943
     Germany                                 596.057             0.0128318
     India                                   27.5693             0.0255019
     Indonesia                                13.733            0.00633481
     Italy                                   695.283             0.0172426
     Japan                                   364.139            0.00956063
...                                              ...                   ...
2015 Indonesia                                29.659            0.00886273
     Italy                                   423.004              0.013957
     Japan                                   324.738            0.00991031
     Korea, South                            724.402             0.0264412
     Mexico                                  60.9329            0.00676652
     Russian Federation                      462.987              0.049026
     Saudi Arabia                            2764.26              0.134962
     South Africa                            63.5016             0.0109333
     Turkey                                  201.878             0.0221115
     UK                                      832.288             0.0189138
     USA                                     1852.26             0.0330443
2016 Argentina                               118.795            0.00956362
     Australia                                1012.7             0.0197131
     Brazil                                  112.969              0.013392
     Canada                                   417.76            0.00995238
     China, P.R.                             155.744             0.0193193
     France                                  862.358             0.0227273
     Germany                                  509.33             0.0119053
     India                                   42.1404             0.0249985
     Indonesia                                31.392            0.00865894
     Italy                                   467.448             0.0151961
     Japan                                   365.395            0.00988961
     Korea, South                            728.797             0.0265324
     Mexico                                   46.775            0.00582742
     Russian Federation                      483.114             0.0531703
     Saudi Arabia                            1978.19              0.104135
     South Africa                            57.4532             0.0108048
     Turkey                                  185.892             0.0198854
     UK                                      741.312             0.0185852
     USA                                     1886.16             0.0329269

                        Military_spending          Gdp      Pop
Year Country
2007 Argentina                    2296.45       262451  39.9699
     Australia                    17186.4       946379  20.9759
     Brazil                       20485.8  1.36685e+06  192.785
     Canada                       17417.1  1.42578e+06  32.9823
     China, P.R.                  68011.6  3.54236e+06  1319.63
     France                         60595  2.66413e+06  61.9662
     Germany                      42551.9   3.4355e+06  80.8545
     India                        28254.8  1.20611e+06  1179.69
     Indonesia                    3348.76       432216  232.297
     Italy                        35961.7  2.20397e+06  59.1386
     Japan                          40530  4.35633e+06   127.25
     Korea, South                 27726.1  1.11917e+06  48.2051
     Mexico                       4779.84  1.04313e+06  113.139
     Russian Federation             43535  1.28492e+06   143.18
     Saudi Arabia                 35469.5       415965  26.0835
     South Africa                 3525.68       286169  49.6936
     Turkey                       15319.2       647140  69.5155
     UK                           65986.1  2.96326e+06  61.1518
     USA                           556961  1.44776e+07  301.656
2008 Argentina                    2788.98       330196  40.3819
     Australia                    18633.1  1.03605e+06  21.3703
     Brazil                       24452.9  1.65353e+06   194.77
     Canada                       19342.1  1.50179e+06  33.3633
     China, P.R.                  86362.1  4.56451e+06  1326.69
     France                       66009.4  2.92151e+06  62.3095
     Germany                      48081.4  3.74705e+06  80.6659
     India                        33002.4  1.29411e+06  1197.07
     Indonesia                     3232.2       510229  235.361
     Italy                        41243.6  2.39196e+06  59.3192
     Japan                        46361.5  4.84921e+06  127.318
...                                   ...          ...      ...
2015 Indonesia                     7639.1       861935  257.564
     Italy                        25294.6  1.81233e+06  59.7977
     Japan                        41103.2  4.14752e+06  126.573
     Korea, South                 36432.7  1.37787e+06  50.2934
     Mexico                       7739.52   1.1438e+06  127.017
     Russian Federation           66418.7  1.35476e+06  143.457
     Saudi Arabia                 87185.9       646003  31.5404
     South Africa                 3460.23       316485  54.4904
     Turkey                       15880.9       718221  78.6658
     UK                           53862.2  2.84777e+06  64.7158
     USA                           596010  1.80367e+07  321.774
2016 Argentina                    5209.26       544696  43.8508
     Australia                    24616.9  1.24876e+06  24.3082
     Brazil                       23675.8  1.76791e+06  209.578
     Canada                       15157.5    1.523e+06  36.2827
     China, P.R.                   215176  1.11379e+07   1381.6
     France                       55745.5   2.4528e+06  64.6431
     Germany                      41067.5   3.4495e+06  80.6303
     India                        55923.2  2.23706e+06  1327.07
     Indonesia                    8183.42       945084  260.685
     Italy                        27933.8  1.83823e+06   59.758
     Japan                        46126.3  4.66412e+06  126.237
     Korea, South                 36776.7  1.38611e+06  50.4623
     Mexico                       6019.77  1.03301e+06  128.696
     Russian Federation           69245.3  1.30233e+06  143.331
     Saudi Arabia                 63672.8       611443  32.1874
     South Africa                    3160       292462  55.0014
     Turkey                       14802.9       744408  79.6316
     UK                           48252.5  2.59628e+06  65.0907
     USA                           611186  1.85619e+07  324.037

[190 rows x 5 columns]